### ISSUE TITLE
fund wallet - POST http://localhost:4180/v2/transactions 400 (Bad Request)

### ISSUE THREAD

**Issue by stanleyseow** [nicholasburka/reach-vue-tutorial#2]
Got this error...

Version 
shared_backend.mjs?a5c1:190 Uncaught TypeError: Cannot read properties of undefined (reading 'utils')
    at Module.eval (shared_backend.mjs?a5c1:190:1)
    at eval (shared_backend.mjs:471:30)
    at ./node_modules/@reach-sh/stdlib/shared_backend.mjs (chunk-vendors.js:1509:1)
    at __webpack_require__ (app.js:849:30)
    at fn (app.js:151:20)
    at eval (CBR.mjs?b12d:1:1)
    at ./node_modules/@reach-sh/stdlib/CBR.mjs (chunk-vendors.js:1497:1)
    at __webpack_require__ (app.js:849:30)
    at fn (app.js:151:20)
    at eval (shared_impl.mjs?9663:1:1)

**Comment by nicholasburka** [comment]
did you figure this out?

i haven't updated the code from this since i released it, and the reach and algo versions have advanced significantly. likely the code requires revision, which i would like to do but don't know when i will. thanks for your issue

**Comment by nicholasburka** [comment]
did not mean to close

**Comment by stanleyseow** [comment]
I fixed this error .. the syntax changed ...

//import * as reach from '@reach-sh/stdlib/ALGO.mjs'
import { loadStdlib } from '@reach-sh/stdlib';
const reach = loadStdlib("ALGO");

**Comment by nicholasburka** [comment]
thanks for the update stanley!
